Update Regular_expression_Denial_of_Service_-_ReDoS.md
OWASP/www-community pull request #377
Opened 2021-02-27 00:24 UTC by pi3ch

Reworded to use correct terminologies. Fixed wording consistency. Included the missing root-cause of the example that was to do with `backtracking` which is different from `back-referencing`. 
Overall, this guide needs improvement and lacks clarity. I may have another go later.

2021-02-27 00:42 UTC, kingthorin requested changes
Thanks for tackling this. We're happy for any improvements big or small.

2021-02-27 00:42 UTC, kingthorin commented on pages/attacks/Regular_expression_Denial_of_Service_-_ReDoS.md
> +A Regex pattern is called **Evil Regex** if it can stuck on crafted input.
```suggestion
A Regex pattern is called **Evil Regex** if it can get stuck on crafted input.
```

Or "become"

2021-03-17 19:47 UTC, Cu2y approved these changes

2021-04-13 21:13 UTC, kingthorin commented
@pi3ch do you plan to finish this?

2021-04-18 23:16 UTC, pi3ch commented
@kingthorin sorry, do you mean the typo fix?

2021-04-18 23:41 UTC, kingthorin commented
The change suggested in the previous review

https://github.com/OWASP/www-community/pull/377#pullrequestreview-600048041

2021-04-18 23:42 UTC, kingthorin commented
The missing word

2021-04-19 16:56 UTC, kingthorin commented
@pi3ch The text wasn’t corrected, you either need to commit the suggestion or add your own commit doing it.

2021-08-02 00:20 UTC, merged