Updating Attacks: Credential Stuffing
OWASP/www-community pull request #468
Opened 2021-08-18 10:51 UTC by nickmalcolm

This is in response to the request for contributions put out on OWASP Slack. This has hopefully clearer language, verifiable & better referenced claims, and a clearer diagram.

1) Follow the likes of the XSS page in structure
2) Remove some verbosity and jargon to hopefully make it more accessible to people
3) Update references with newer sources
4) Update the diagram to actually show credential stuffing
5) Add references to other OWASP pages (brute forcing & password spraying)

2021-08-18 11:57 UTC, kingthorin requested changes
Thanks for tackling this, just a few minor things.

2021-08-18 11:57 UTC, kingthorin commented on pages/attacks/Credential_stuffing.md
> +1.  Draining stolen accounts of stored value or making purchases
```suggestion
1.  Draining stolen accounts of stored value or making purchases.
```

2021-08-18 11:57 UTC, kingthorin commented on pages/attacks/Credential_stuffing.md
> +2.  Accessing sensitive information such as credit card numbers, private messages or pictures, or documents
```suggestion
2.  Accessing sensitive information such as credit card numbers, private messages, pictures, or documents.
```

2021-08-18 11:57 UTC, kingthorin commented on pages/attacks/Credential_stuffing.md
> +3.  Using the account to send phishing messages or spam
```suggestion
3.  Using the account to send phishing messages or spam.
```

2021-08-18 11:57 UTC, kingthorin commented on pages/attacks/Credential_stuffing.md
> +4.  Selling known-valid credentials to one or more of the compromised sites for other attackers to use
```suggestion
4.  Selling known-valid credentials to one or more of the compromised sites for other attackers to use.
```

2021-08-19 01:20 UTC, kingthorin approved these changes
Thanks!

2021-08-19 01:20 UTC, merged

2021-08-19 02:09 UTC, nickmalcolm commented
No worries! Good team work! 🙌🏻