Suggested clarifications for Source Code Tools page
OWASP/www-community pull request #482
Opened 2021-09-07 14:48 UTC by mjang-cobalt

* PR Author: Mike Jang

2021-09-07 14:50 UTC, mjang-cobalt commented on pages/Source_Code_Analysis_Tools.md
> -Some tools are starting to move into the IDE. For the types of problems that can be detected during the software development phase itself, this is a powerful phase within the development life cycle t
I think OWASP does not need to discuss details of the Software Development Life Cycle.

2021-09-07 14:52 UTC, mjang-cobalt commented on pages/Source_Code_Analysis_Tools.md
> +- Identifies certain well-known vulnerabilities, such as:
I've limited the list to what's known. If the audience is developers, I think "code snippet" is more appropriate than "subsections of lines"

2021-09-07 14:53 UTC, mjang-cobalt commented on pages/Source_Code_Analysis_Tools.md
>  - Frequently can't find configuration issues, since they are not represented in the code.
```suggestion
- Frequently unable to find configuration issues, since they are not represented in the code.
```

2021-09-07 14:55 UTC, mjang-cobalt commented on pages/Source_Code_Analysis_Tools.md
> +    - All required code
I'm not convinced that any of this detail is needed. It's somewhat redundant to "analyzing code that can't be compiled".

2021-09-07 14:58 UTC, mjang-cobalt commented on pages/Source_Code_Analysis_Tools.md
> +  - Other criteria
You could include examples: 

```suggestion
  - Other criteria such as [OSSTMM](https://www.isecom.org/OSSTMM.3.pdf) and [CHECK](https://www.ncsc.gov.uk/information/check-penetration-testing)
```

2021-09-07 15:09 UTC, kingthorin requested changes

2021-09-07 15:09 UTC, kingthorin commented on pages/Source_Code_Analysis_Tools.md
> +[Source code analysis](Static_Code_Analysis) tools, also known as Static Application Security Testing (SAST) Tools, can help you analyze source code or compiled versions of code to help find security
```suggestion
[Source code analysis](Static_Code_Analysis) tools, also known as Static Application Security Testing (SAST) Tools, can help analyze source code or compiled versions of code to help find security flaws.
```

2021-09-07 15:09 UTC, kingthorin commented on pages/Source_Code_Analysis_Tools.md
> +You can add some SAST tools into your IDE. Such tools can help you detect issues during software development.
```suggestion
SAST tools can be added into your IDE. Such tools can help you detect issues during software development.
```

2021-09-07 15:09 UTC, kingthorin commented on pages/Source_Code_Analysis_Tools.md
> +  - SQL Injection Flaws
```suggestion
  - SQL injection flaws
```

2021-09-07 15:22 UTC, mjang-cobalt commented
Thanks for reviewing, @kingthorin . I think I've accepted your requested changes.

2021-09-07 15:29 UTC, kingthorin approved these changes
Thanks!

2021-09-07 15:30 UTC, merged

2025-08-05 13:56 UTC, willofpath approved these changes