Create ip_spoofing_via_http_headers.md
OWASP/www-community pull request #869
Opened 2024-02-01 23:22 UTC by Ahmad-Reza-UT

2024-02-01 23:46 UTC, kingthorin commented
Why do you keep creating new PRs? You already have two open for this content.

2024-02-02 08:18 UTC, Ahmad-Reza-UT commented
I am sorry
This is my first time so I am not well aware about it.

But I edited all the problems

On Fri, Feb 2, 2024, 3:17 AM Rick M ***@***.***> wrote:

> Why do you keep creating new PRs? You already have two open for this
> content.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/www-community/pull/869#issuecomment-1922500871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX66WMJUNWGILHCTEEO7KJLYRQSPPAVCNFSM6AAAAABCVYD77OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRSGUYDAOBXGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-02 08:19 UTC, Ahmad-Reza-UT commented
> Why do you keep creating new PRs? You already have two open for this content.

I am sorry I wasn't aware about it and This is my first time but I have edited ethe issues yiu mentioned before

2024-02-02 13:33 UTC, kingthorin requested changes
Please do not open another PR simply re-edit the content associated with this one.

2024-02-02 13:33 UTC, kingthorin commented on pages/attacks/ip_spoofing_via_http_headers.md
> +Internet Protocol (IP) spoofing is a type of malicious attack where the threat actor hides the true source of IP packets to make it difficult to know where they came from. The attacker creates packet
This has zero to do with headers

2024-02-02 13:33 UTC, kingthorin commented on pages/attacks/ip_spoofing_via_http_headers.md
> +### Workflow
This doesn't outline a workflow

2024-02-02 13:33 UTC, kingthorin commented on pages/attacks/ip_spoofing_via_http_headers.md
> +1. ### DDoS Attacks
This has nothing to do with headers

2024-02-07 01:40 UTC, Ahmad-Reza-UT commented
How long does it take to review my article?

2024-02-07 01:41 UTC, Ahmad-Reza-UT commented
I have edited all the things you mentioned

2024-02-07 15:51 UTC, kingthorin commented
Thanks. This content is handled by volunteers. So there's no SLA.

I'll try to have another look at it this evening.

2024-02-08 18:23 UTC, kingthorin approved these changes

2024-02-08 18:23 UTC, merged